-- Templates de tarefas automáticas por etapa do funil
CREATE TABLE public.funil_automacoes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  etapa_id bigint NOT NULL REFERENCES public.funil_etapas(id) ON DELETE CASCADE,
  descricao text NOT NULL,
  dias_vencimento integer DEFAULT 0,
  ordem integer DEFAULT 0,
  empresa_id bigint NOT NULL REFERENCES public.configuracoes_empresa(id),
  created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.funil_automacoes ENABLE ROW LEVEL SECURITY;

CREATE POLICY automacoes_select ON public.funil_automacoes
  FOR SELECT TO authenticated
  USING (empresa_id = get_my_empresa_id());

CREATE POLICY automacoes_insert ON public.funil_automacoes
  FOR INSERT TO authenticated
  WITH CHECK (
    empresa_id = get_my_empresa_id()
    AND is_admin_of_my_empresa()
  );

CREATE POLICY automacoes_update ON public.funil_automacoes
  FOR UPDATE TO authenticated
  USING (empresa_id = get_my_empresa_id() AND is_admin_of_my_empresa())
  WITH CHECK (empresa_id = get_my_empresa_id() AND is_admin_of_my_empresa());

CREATE POLICY automacoes_delete ON public.funil_automacoes
  FOR DELETE TO authenticated
  USING (empresa_id = get_my_empresa_id() AND is_admin_of_my_empresa());

CREATE INDEX idx_funil_automacoes_etapa ON public.funil_automacoes(etapa_id);
CREATE INDEX idx_funil_automacoes_empresa ON public.funil_automacoes(empresa_id);
