-- Função auxiliar SECURITY DEFINER para obter o ID do usuário logado
-- Bypassa RLS da tabela users, evitando recursão infinita
create or replace function public.get_my_user_id()
returns bigint
language sql
security definer
set search_path = public
stable
as $$
  select id from users where auth_id = auth.uid() limit 1;
$$;

grant execute on function public.get_my_user_id() to authenticated;

create table public.buscas_realizadas (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  segmento text null,
  localizacao text null,
  tipo_pesquisa text null,
  "user" bigint null,
  constraint buscas_realizadas_pkey primary key (id),
  constraint buscas_realizadas_user_fkey foreign key ("user") references users (id)
) tablespace pg_default;

alter table public.buscas_realizadas enable row level security;

create policy "Usuários podem inserir suas próprias buscas"
  on public.buscas_realizadas for insert
  with check ("user" = public.get_my_user_id());

create policy "Usuários podem ver suas próprias buscas"
  on public.buscas_realizadas for select
  using ("user" = public.get_my_user_id());
