-- ================================================================
-- Super Admin Backoffice: planos, assinaturas, pagamentos
-- ================================================================

-- Tabela de planos do sistema
CREATE TABLE IF NOT EXISTS public.planos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome text NOT NULL,
  descricao text,
  preco_mensal numeric(10,2) NOT NULL DEFAULT 0,
  preco_anual numeric(10,2) NOT NULL DEFAULT 0,
  max_usuarios integer NOT NULL DEFAULT 5,
  max_leads integer NOT NULL DEFAULT 1000,
  max_buscas_mes integer NOT NULL DEFAULT 100,
  recursos text[] DEFAULT '{}',
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Tabela de assinaturas (uma por empresa)
CREATE TABLE IF NOT EXISTS public.assinaturas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id bigint NOT NULL REFERENCES public.configuracoes_empresa(id) ON DELETE CASCADE,
  plano_id bigint NOT NULL REFERENCES public.planos(id),
  status text NOT NULL DEFAULT 'ativa' CHECK (status IN ('ativa','vencida','cancelada','trial','suspensa')),
  ciclo text NOT NULL DEFAULT 'mensal' CHECK (ciclo IN ('mensal','anual')),
  valor numeric(10,2) NOT NULL DEFAULT 0,
  data_inicio timestamptz NOT NULL DEFAULT now(),
  data_vencimento timestamptz NOT NULL,
  data_cancelamento timestamptz,
  observacoes text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Tabela de pagamentos
CREATE TABLE IF NOT EXISTS public.pagamentos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assinatura_id bigint NOT NULL REFERENCES public.assinaturas(id) ON DELETE CASCADE,
  empresa_id bigint NOT NULL REFERENCES public.configuracoes_empresa(id) ON DELETE CASCADE,
  valor numeric(10,2) NOT NULL,
  status text NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente','pago','atrasado','cancelado')),
  data_vencimento timestamptz NOT NULL,
  data_pagamento timestamptz,
  metodo_pagamento text,
  referencia text,
  observacoes text,
  created_at timestamptz DEFAULT now()
);

-- Planos padrão
INSERT INTO public.planos (nome, descricao, preco_mensal, preco_anual, max_usuarios, max_leads, max_buscas_mes, recursos)
VALUES
  ('Básico', 'Ideal para pequenas equipes', 97.00, 970.00, 3, 500, 50, ARRAY['Dashboard','Funil básico','Busca Google Maps']),
  ('Premium', 'Para equipes em crescimento', 197.00, 1970.00, 10, 2000, 200, ARRAY['Dashboard','Funil avançado','Busca Google Maps','Busca Instagram','Relatórios','Ranking']),
  ('Empresarial', 'Para grandes operações', 397.00, 3970.00, 50, 10000, 1000, ARRAY['Dashboard','Funil avançado','Busca Google Maps','Busca Instagram','Relatórios','Ranking','API','Suporte prioritário'])
ON CONFLICT DO NOTHING;

-- Função para verificar se é super_admin
CREATE OR REPLACE FUNCTION public.is_super_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.users
     WHERE auth_id = auth.uid()
       AND role = 'super_admin'
  );
$$;

-- RLS para planos (super_admin pode tudo, outros só leem ativos)
ALTER TABLE public.planos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "planos_select_all" ON public.planos
  FOR SELECT USING (true);

CREATE POLICY "planos_manage_super_admin" ON public.planos
  FOR ALL USING (public.is_super_admin());

-- RLS para assinaturas
ALTER TABLE public.assinaturas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "assinaturas_select_own" ON public.assinaturas
  FOR SELECT USING (
    empresa_id = public.get_my_empresa_id()
    OR public.is_super_admin()
  );

CREATE POLICY "assinaturas_manage_super_admin" ON public.assinaturas
  FOR ALL USING (public.is_super_admin());

-- RLS para pagamentos
ALTER TABLE public.pagamentos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "pagamentos_select_own" ON public.pagamentos
  FOR SELECT USING (
    empresa_id = public.get_my_empresa_id()
    OR public.is_super_admin()
  );

CREATE POLICY "pagamentos_manage_super_admin" ON public.pagamentos
  FOR ALL USING (public.is_super_admin());
