-- Histórico de movimentações dos leads entre etapas do funil
CREATE TABLE public.funil_logs_movimentacao (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id bigint NOT NULL REFERENCES public.leads_captados(id) ON DELETE CASCADE,
  etapa_id bigint NOT NULL REFERENCES public.funil_etapas(id) ON DELETE CASCADE,
  data_entrada timestamp with time zone DEFAULT now(),
  user_id bigint NOT NULL REFERENCES public.users(id)
);

ALTER TABLE public.funil_logs_movimentacao ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users_manage_own_logs" ON public.funil_logs_movimentacao
  FOR ALL TO authenticated
  USING (user_id = public.get_my_user_id())
  WITH CHECK (user_id = public.get_my_user_id());

CREATE INDEX idx_funil_logs_lead ON public.funil_logs_movimentacao(lead_id);
CREATE INDEX idx_funil_logs_etapa ON public.funil_logs_movimentacao(etapa_id);
CREATE INDEX idx_funil_logs_data ON public.funil_logs_movimentacao(data_entrada DESC);
