-- Remove funil_tarefas (depende de funil_negocios)
DROP TABLE IF EXISTS public.funil_tarefas;

-- Remove funil_negocios (não será mais usada)
DROP TABLE IF EXISTS public.funil_negocios;

-- Adiciona colunas de funil em leads_captados
ALTER TABLE public.leads_captados
  ADD COLUMN IF NOT EXISTS etapa_id bigint REFERENCES public.funil_etapas(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS valor numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS contato text,
  ADD COLUMN IF NOT EXISTS notas text,
  ADD COLUMN IF NOT EXISTS status_funil text DEFAULT 'em_andamento',
  ADD COLUMN IF NOT EXISTS ordem_funil integer DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_leads_captados_etapa ON public.leads_captados(etapa_id);

-- Recria funil_tarefas referenciando leads_captados
CREATE TABLE public.funil_tarefas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id bigint NOT NULL REFERENCES public.leads_captados(id) ON DELETE CASCADE,
  descricao text NOT NULL,
  data_vencimento timestamp with time zone,
  concluida boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.funil_tarefas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users_manage_own_tarefas" ON public.funil_tarefas
  FOR ALL TO authenticated
  USING (
    lead_id IN (
      SELECT id FROM public.leads_captados WHERE user_id = public.get_my_user_id()
    )
  )
  WITH CHECK (
    lead_id IN (
      SELECT id FROM public.leads_captados WHERE user_id = public.get_my_user_id()
    )
  );

CREATE INDEX idx_funil_tarefas_lead ON public.funil_tarefas(lead_id);
