-- Etapas do funil comercial (colunas do Kanban)
CREATE TABLE public.funil_etapas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome text NOT NULL,
  ordem integer NOT NULL DEFAULT 0,
  cor text DEFAULT '#3b82f6',
  user_id bigint NOT NULL REFERENCES public.users(id),
  created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.funil_etapas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users_manage_own_etapas" ON public.funil_etapas
  FOR ALL TO authenticated
  USING (user_id = public.get_my_user_id())
  WITH CHECK (user_id = public.get_my_user_id());

CREATE INDEX idx_funil_etapas_user ON public.funil_etapas(user_id);

-- Negociações (cards do Kanban)
CREATE TABLE public.funil_negocios (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo text NOT NULL,
  empresa text,
  valor numeric DEFAULT 0,
  etapa_id bigint NOT NULL REFERENCES public.funil_etapas(id) ON DELETE CASCADE,
  lead_id bigint REFERENCES public.leads_captados(id) ON DELETE SET NULL,
  contato text,
  telefone text,
  email text,
  notas text,
  status text DEFAULT 'em_andamento',
  ordem integer NOT NULL DEFAULT 0,
  user_id bigint NOT NULL REFERENCES public.users(id),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.funil_negocios ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users_manage_own_negocios" ON public.funil_negocios
  FOR ALL TO authenticated
  USING (user_id = public.get_my_user_id())
  WITH CHECK (user_id = public.get_my_user_id());

CREATE INDEX idx_funil_negocios_etapa ON public.funil_negocios(etapa_id);
CREATE INDEX idx_funil_negocios_user ON public.funil_negocios(user_id);

-- Tarefas vinculadas a negociações
CREATE TABLE public.funil_tarefas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  negocio_id bigint NOT NULL REFERENCES public.funil_negocios(id) ON DELETE CASCADE,
  descricao text NOT NULL,
  data_vencimento timestamp with time zone,
  concluida boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.funil_tarefas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users_manage_own_tarefas" ON public.funil_tarefas
  FOR ALL TO authenticated
  USING (
    negocio_id IN (
      SELECT id FROM public.funil_negocios WHERE user_id = public.get_my_user_id()
    )
  )
  WITH CHECK (
    negocio_id IN (
      SELECT id FROM public.funil_negocios WHERE user_id = public.get_my_user_id()
    )
  );

CREATE INDEX idx_funil_tarefas_negocio ON public.funil_tarefas(negocio_id);
