-- Tabela de leads captados pelo usuário
CREATE TABLE public.leads_captados (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT now(),

  -- Dados do lead
  nome text NOT NULL,
  endereco text,
  telefone text,
  email text,
  website text,
  rating numeric,
  avaliacoes integer DEFAULT 0,
  has_whatsapp boolean,
  whatsapp_status text,
  tags text[] DEFAULT '{}',

  -- Metadados da captação
  data_captacao timestamp with time zone DEFAULT now(),
  origem_busca text,
  segmento_busca text,
  localizacao_busca text,

  -- Coordenadas
  latitude numeric,
  longitude numeric,

  -- Dono do lead (usa get_my_user_id para evitar recursão RLS)
  user_id bigint NOT NULL REFERENCES public.users(id)
);

ALTER TABLE public.leads_captados ENABLE ROW LEVEL SECURITY;

-- Usa get_my_user_id() (SECURITY DEFINER) para evitar recursão infinita nas policies
CREATE POLICY "users_insert_own_leads"
  ON public.leads_captados
  FOR INSERT
  TO authenticated
  WITH CHECK (user_id = public.get_my_user_id());

CREATE POLICY "users_select_own_leads"
  ON public.leads_captados
  FOR SELECT
  TO authenticated
  USING (user_id = public.get_my_user_id());

CREATE POLICY "users_update_own_leads"
  ON public.leads_captados
  FOR UPDATE
  TO authenticated
  USING (user_id = public.get_my_user_id())
  WITH CHECK (user_id = public.get_my_user_id());

CREATE POLICY "users_delete_own_leads"
  ON public.leads_captados
  FOR DELETE
  TO authenticated
  USING (user_id = public.get_my_user_id());

CREATE INDEX idx_leads_captados_user ON public.leads_captados(user_id);
CREATE INDEX idx_leads_captados_data ON public.leads_captados(data_captacao DESC);
